[options]
addons_path = /mnt/addons_library
data_dir = /var/lib/odoo
proxy_mode = True
admin_passwd = $pbkdf2-sha512$600000$3TtHqNX6X6tVag3B2Lt3Dg$w5No2koBUoAayDYpyqThvWw.0R1ic5w1PExEXPI0s.MBmzF5Z1aKSgajXouzR7Hw0Fs7GiQvoKrV.CUB9Rz39w

