[options]
addons_path = /mnt/addons_library
data_dir = /var/lib/odoo
proxy_mode = True
admin_passwd = $pbkdf2-sha512$600000$WCuF8B6DcC5lTInRWusdYw$EK.4CpFjAl2yFIDWRxz1sE/KXQ2oHh7m5YqIDaRO7WGxGlcTNNN5Z4UW1/qO8ms/XzHAlMfDvuUifhXu03MS.g

